# Kusogarch - Default Window Rules (Immutable)

windowrulev2 = float, class:^(gnome-calculator)$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = float, title:^(Open File)$
windowrulev2 = float, title:^(Save As)$

# Kusogarch menu windows
windowrulev2 = float, class:^(kusogarch-menu)$
windowrulev2 = size 700 500, class:^(kusogarch-menu)$
windowrulev2 = center, class:^(kusogarch-menu)$

# Floating kitty
windowrulev2 = float, class:^(kitty-float)$
windowrulev2 = size 800 500, class:^(kitty-float)$
windowrulev2 = center, class:^(kitty-float)$
