#!/bin/bash
# Kusogarch - Deploy user config files to ~/.config/

log_info "Deploying configuration files..."

CONFIG_SRC="$KUSOGARCH_DIR/config"
CONFIG_DST="$HOME/.config"

# Create directories
mkdir -p "$CONFIG_DST"/{hypr/bindings,waybar,walker,fuzzel,kitty,mako,btop,fastfetch,gtk-3.0,gtk-4.0}
mkdir -p "$CONFIG_DST"/kusogarch/{current,themes}

# Deploy config files (do not overwrite existing user files)
while IFS= read -r -d '' src; do
    relative="${src#$CONFIG_SRC/}"
    copy_no_overwrite "$src" "$CONFIG_DST/$relative"
done < <(find "$CONFIG_SRC" -type f -print0)

# envs-vm.conf: Hyprland always sources this file. Populate it if in a VM.
VM_ENVS="$CONFIG_DST/hypr/envs-vm.conf"
if is_vm; then
    cat > "$VM_ENVS" << 'VMEOF'
# Kusogarch - Virtual machine environment overrides (auto-generated)
# These flags enable Hyprland to run without GPU hardware acceleration.
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = WLR_NO_HARDWARE_CURSORS,1
env = LIBGL_ALWAYS_SOFTWARE,true
env = WLR_RENDERER,pixman
VMEOF
    log_step "VM detected — enabled software rendering in envs-vm.conf"
elif [ ! -f "$VM_ENVS" ]; then
    echo "# Kusogarch - No VM detected, no overrides needed" > "$VM_ENVS"
fi

# input-surface.conf: Hyprland always sources this file, so it MUST exist.
# In Desktop mode, create an empty placeholder so Hyprland doesn't crash.
SURFACE_INPUT="$CONFIG_DST/hypr/input-surface.conf"
if [ ! -f "$SURFACE_INPUT" ]; then
    echo "# No Surface input config (desktop mode)" > "$SURFACE_INPUT"
    log_step "Created empty input-surface.conf placeholder"
fi

# === Theme Selection ===
log_info "Theme selection..."

# Discover available themes (directories with colors.toml, skip template)
THEME_NAMES=()
for theme_dir in "$KUSOGARCH_DIR/themes"/*/; do
    [ -d "$theme_dir" ] || continue
    theme_name=$(basename "$theme_dir")
    [ "$theme_name" = "template" ] && continue
    THEME_NAMES+=("$theme_name")
done

# Sort: put "default" first, then alphabetical
THEME_LIST=("default")
for name in $(printf '%s\n' "${THEME_NAMES[@]}" | sort); do
    [ "$name" = "default" ] && continue
    THEME_LIST+=("$name")
done

echo ""
THEME_CHOICE=$(choose "Select a theme for your desktop:" "${THEME_LIST[@]}")
CHOSEN_THEME="${THEME_LIST[$((THEME_CHOICE - 1))]}"
log_step "Selected theme: $CHOSEN_THEME"

CHOSEN_THEME_DIR="$KUSOGARCH_DIR/themes/$CHOSEN_THEME"

# Auto-generate missing theme files if only colors.toml exists
if [ -f "$CHOSEN_THEME_DIR/colors.toml" ]; then
    if [ ! -f "$CHOSEN_THEME_DIR/hyprland.conf" ] || [ ! -f "$CHOSEN_THEME_DIR/qt.colors" ] || [ ! -f "$CHOSEN_THEME_DIR/gtk.css" ]; then
        log_step "Generating theme files from colors.toml..."
        "$KUSOGARCH_DIR/bin/kusogarch-theme-generate" "$CHOSEN_THEME_DIR"
    fi
fi

# Set up theme symlink
THEME_LINK="$CONFIG_DST/kusogarch/current/theme"
rm -f "$THEME_LINK"
ln -sf "$CHOSEN_THEME_DIR" "$THEME_LINK"
echo "$CHOSEN_THEME" > "$CONFIG_DST/kusogarch/current/theme.name"
log_step "Set theme: $CHOSEN_THEME"

# Verify theme symlink target exists
if [ -L "$THEME_LINK" ] && [ ! -e "$THEME_LINK" ]; then
    log_warn "Theme symlink broken, resetting to default"
    rm -f "$THEME_LINK"
    ln -sf "$KUSOGARCH_DIR/themes/default" "$THEME_LINK"
    echo "default" > "$CONFIG_DST/kusogarch/current/theme.name"
    CHOSEN_THEME="default"
    CHOSEN_THEME_DIR="$KUSOGARCH_DIR/themes/default"
fi

# Resolve hyprqt6engine color scheme path (~ is not expanded by Qt plugins)
# Points to symlink path so Qt colors change automatically with theme
HYPRQT6_CONF="$CONFIG_DST/hypr/hyprqt6engine.conf"
if [ -f "$HYPRQT6_CONF" ] && grep -q 'PLACEHOLDER_COLOR_SCHEME' "$HYPRQT6_CONF"; then
    QT_COLORS_PATH="$CONFIG_DST/kusogarch/current/theme/qt.colors"
    sed -i "s|PLACEHOLDER_COLOR_SCHEME|$QT_COLORS_PATH|" "$HYPRQT6_CONF"
    log_step "hyprqt6engine color scheme path resolved (via theme symlink)"
fi

# Initialize GTK theme CSS from chosen theme
CHOSEN_GTK_CSS="$CHOSEN_THEME_DIR/gtk.css"
if [ -f "$CHOSEN_GTK_CSS" ]; then
    cp "$CHOSEN_GTK_CSS" "$CONFIG_DST/gtk-3.0/gtk.css"
    cp "$CHOSEN_GTK_CSS" "$CONFIG_DST/gtk-4.0/gtk.css"
    log_step "GTK theme CSS initialized ($CHOSEN_THEME)"
fi

# Initialize kdeglobals from chosen theme
CHOSEN_QT_COLORS="$CHOSEN_THEME_DIR/qt.colors"
if [ -f "$CHOSEN_QT_COLORS" ]; then
    cp "$CHOSEN_QT_COLORS" "$CONFIG_DST/kdeglobals"
    log_step "kdeglobals initialized from $CHOSEN_THEME theme"
fi

# Generate hyprpaper.conf with wallpaper path
HYPRPAPER_CONF="$CONFIG_DST/hypr/hyprpaper.conf"
WALLPAPER=""
for candidate in \
    "$CHOSEN_THEME_DIR/wallpaper.png" \
    "$CHOSEN_THEME_DIR/wallpaper.jpg" \
    "$KUSOGARCH_DIR/themes/default/wallpaper.png" \
    "$KUSOGARCH_DIR/themes/default/wallpaper.jpg" \
    "$KUSOGARCH_DIR/wallpapers"/*.jpg \
    "$KUSOGARCH_DIR/wallpapers"/*.png; do
    if [ -f "$candidate" ]; then
        WALLPAPER="$candidate"
        break
    fi
done

if [ -n "$WALLPAPER" ]; then
    cat > "$HYPRPAPER_CONF" << EOF
# Kusogarch - Hyprpaper (auto-generated by dotfiles.sh)
preload = $WALLPAPER
wallpaper = ,$WALLPAPER
splash = false
EOF
    if is_vm; then
        log_step "Wallpaper configured (swaybg mode — VM detected)"
    else
        log_step "Wallpaper configured (hyprpaper mode)"
    fi
else
    cat > "$HYPRPAPER_CONF" << 'EOF'
# Kusogarch - Hyprpaper (no wallpaper found)
splash = false
EOF
    log_step "No wallpaper found, hyprpaper.conf created empty"
fi

# Deploy web app .desktop files with icons
APPS_SRC="$KUSOGARCH_DIR/applications"
APPS_DST="$HOME/.local/share/applications"
ICONS_DST="$HOME/.local/share/icons/kusogarch"
if [ -d "$APPS_SRC" ]; then
    mkdir -p "$APPS_DST" "$ICONS_DST"
    # Copy icons
    if [ -d "$APPS_SRC/icons" ]; then
        cp "$APPS_SRC/icons/"*.png "$ICONS_DST/" 2>/dev/null
    fi
    # Copy .desktop files and resolve icon path placeholder
    for desktop in "$APPS_SRC"/*.desktop; do
        [ -f "$desktop" ] || continue
        dest="$APPS_DST/$(basename "$desktop")"
        if [ ! -f "$dest" ]; then
            cp "$desktop" "$dest"
            sed -i "s|PLACEHOLDER_ICON_DIR|$ICONS_DST|" "$dest"
        fi
    done
    update-desktop-database "$APPS_DST" 2>/dev/null || true
    log_step "Web app shortcuts deployed"
fi

log_success "Configuration files deployed"
