#!/bin/bash
# Kusogarch - Deploy user config files to ~/.config/

log_info "Deploying configuration files..."

CONFIG_SRC="$KUSOGARCH_DIR/config"
CONFIG_DST="$HOME/.config"

# Create directories
mkdir -p "$CONFIG_DST"/{hypr/bindings,waybar,walker,fuzzel,kitty,mako,btop,fastfetch}
mkdir -p "$CONFIG_DST"/kusogarch/{current,themes}

# Deploy config files (do not overwrite existing user files)
while IFS= read -r -d '' src; do
    relative="${src#$CONFIG_SRC/}"
    copy_no_overwrite "$src" "$CONFIG_DST/$relative"
done < <(find "$CONFIG_SRC" -type f -print0)

# envs-vm.conf: Hyprland always sources this file. Populate it if in a VM.
VM_ENVS="$CONFIG_DST/hypr/envs-vm.conf"
IS_VM="${KUSOGARCH_VM:-false}"
if [ "$IS_VM" != "true" ]; then
    # Also detect at deploy time in case env var isn't set
    if command -v systemd-detect-virt &>/dev/null; then
        VM_TYPE=$(systemd-detect-virt --vm 2>/dev/null || true)
        if [ -n "$VM_TYPE" ] && [ "$VM_TYPE" != "none" ]; then
            IS_VM=true
        fi
    fi
fi
if [ "$IS_VM" = "true" ] || [ "$IS_VM" = true ]; then
    cat > "$VM_ENVS" << 'VMEOF'
# Kusogarch - Virtual machine environment overrides (auto-generated)
# These flags enable Hyprland to run without GPU hardware acceleration.
env = WLR_RENDERER_ALLOW_SOFTWARE,1
env = WLR_NO_HARDWARE_CURSORS,1
env = LIBGL_ALWAYS_SOFTWARE,true
env = WLR_RENDERER,pixman
VMEOF
    log_step "VM detected — enabled software rendering in envs-vm.conf"
elif [ ! -f "$VM_ENVS" ]; then
    echo "# Kusogarch - No VM detected, no overrides needed" > "$VM_ENVS"
fi

# input-surface.conf: Hyprland always sources this file, so it MUST exist.
# In Desktop mode, create an empty placeholder so Hyprland doesn't crash.
SURFACE_INPUT="$CONFIG_DST/hypr/input-surface.conf"
if [ ! -f "$SURFACE_INPUT" ]; then
    echo "# No Surface input config (desktop mode)" > "$SURFACE_INPUT"
    log_step "Created empty input-surface.conf placeholder"
fi

# Set up default theme symlink (remove broken symlinks first)
THEME_LINK="$CONFIG_DST/kusogarch/current/theme"
if [ -L "$THEME_LINK" ] && [ ! -e "$THEME_LINK" ]; then
    rm -f "$THEME_LINK"
    log_step "Removed broken theme symlink"
fi

if [ ! -L "$THEME_LINK" ] && [ ! -d "$THEME_LINK" ]; then
    ln -sf "$KUSOGARCH_DIR/themes/default" "$THEME_LINK"
    echo "default" > "$CONFIG_DST/kusogarch/current/theme.name"
    log_step "Set default theme"
fi

# Verify theme symlink target exists
if [ -L "$THEME_LINK" ] && [ ! -e "$THEME_LINK" ]; then
    log_warn "Theme symlink broken, resetting to default"
    rm -f "$THEME_LINK"
    ln -sf "$KUSOGARCH_DIR/themes/default" "$THEME_LINK"
    echo "default" > "$CONFIG_DST/kusogarch/current/theme.name"
fi

# Generate hyprpaper.conf with wallpaper path
HYPRPAPER_CONF="$CONFIG_DST/hypr/hyprpaper.conf"
WALLPAPER=""
for candidate in \
    "$KUSOGARCH_DIR/themes/default/wallpaper.jpg" \
    "$KUSOGARCH_DIR/themes/default/wallpaper.png" \
    "$KUSOGARCH_DIR/wallpapers"/*.jpg \
    "$KUSOGARCH_DIR/wallpapers"/*.png; do
    if [ -f "$candidate" ]; then
        WALLPAPER="$candidate"
        break
    fi
done

if [ -n "$WALLPAPER" ]; then
    cat > "$HYPRPAPER_CONF" << EOF
# Kusogarch - Hyprpaper (auto-generated by dotfiles.sh)
preload = $WALLPAPER
wallpaper = ,$WALLPAPER
splash = false
EOF
    if [ "$IS_VM" = true ]; then
        log_step "Wallpaper configured (swaybg mode — VM detected)"
    else
        log_step "Wallpaper configured (hyprpaper mode)"
    fi
else
    cat > "$HYPRPAPER_CONF" << 'EOF'
# Kusogarch - Hyprpaper (no wallpaper found)
splash = false
EOF
    log_step "No wallpaper found, hyprpaper.conf created empty"
fi

log_success "Configuration files deployed"
