[theme]
color_scheme = ~/.config/kusogarch/current/theme/catppuccin-mocha.colors
icon_theme = breeze-dark
style = Breeze
font = Noto Sans
font_size = 11
font_fixed = JetBrains Mono Nerd Font
font_fixed_size = 11
